project_id = "gcfyrcpugmducptktjic"
[functions.whatsapp-connect]
enabled = true
verify_jwt = true
import_map = "./functions/whatsapp-connect/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/whatsapp-connect/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/whatsapp-connect/*.html" ]

[functions.whatsapp-qrcode]
enabled = true
verify_jwt = true
import_map = "./functions/whatsapp-qrcode/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/whatsapp-qrcode/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/whatsapp-qrcode/*.html" ]

[functions.whatsapp-status]
enabled = true
verify_jwt = true
import_map = "./functions/whatsapp-status/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/whatsapp-status/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/whatsapp-status/*.html" ]

[functions.whatsapp-send]
enabled = true
verify_jwt = true
import_map = "./functions/whatsapp-send/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/whatsapp-send/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/whatsapp-send/*.html" ]

[functions.whatsapp-campaigns]
enabled = true
verify_jwt = true
entrypoint = "./functions/whatsapp-campaigns/index.ts"

[functions.evogo-webhook]
enabled = true
verify_jwt = false
import_map = "./functions/evogo-webhook/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/evogo-webhook/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/evogo-webhook/*.html" ]

[functions.whatsapp-order-created]
enabled = true
verify_jwt = true
import_map = "./functions/whatsapp-order-created/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/whatsapp-order-created/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/whatsapp-order-created/*.html" ]

[functions.evolution-bot-ai]
enabled = true
verify_jwt = false
entrypoint = "./functions/evolution-bot-ai/index.ts"

[functions.evolution-webhook]
enabled = true
verify_jwt = false
entrypoint = "./functions/evolution-webhook/index.ts"

[functions.waiter-web-auth]
enabled = true
verify_jwt = false
entrypoint = "./functions/waiter-web-auth/index.ts"

[functions.waiter-web]
enabled = true
verify_jwt = false
entrypoint = "./functions/waiter-web/index.ts"

[functions.ifood-webhook]
enabled = true
verify_jwt = false
entrypoint = "./functions/ifood-webhook/index.ts"

[functions.ifood-manager]
enabled = true
verify_jwt = true
entrypoint = "./functions/ifood-manager/index.ts"

[functions.orders-update-status]
enabled = true
verify_jwt = false
entrypoint = "./functions/orders-update-status/index.ts"

[functions.pix-webhook]
enabled = true
verify_jwt = false
entrypoint = "./functions/pix-webhook/index.ts"
