create table if not exists public.push_subscriptions (
    id bigint generated by default as identity primary key,
    created_at timestamp with time zone not null default now(),
    user_id uuid references auth.users on delete cascade,
    endpoint text not null unique,
    keys jsonb not null
);

alter table public.push_subscriptions enable row level security;

create policy "Users can insert their own subscriptions"
    on public.push_subscriptions for insert
    with check (auth.uid() = user_id);

create policy "Users can view their own subscriptions"
    on public.push_subscriptions for select
    using (auth.uid() = user_id);

create policy "Users can update their own subscriptions"
    on public.push_subscriptions for update
    using (auth.uid() = user_id);

create policy "Users can delete their own subscriptions"
    on public.push_subscriptions for delete
    using (auth.uid() = user_id);

-- Policy for Service Role (Edge Functions)
create policy "Service role can do everything"
    on public.push_subscriptions
    using (true)
    with check (true);
